export { Explore } from "./Explore";
export { Home } from "./Home";
export { Login } from "./Login";
export { Signup } from "./Signup";
// export { CreatePost } from "./CreatePost";
// export { EditPost } from "./EditPost";
// export { Profile } from "./Profile";
// export { EditProfile } from "./EditProfile";
// export { PostDetail } from "./PostDetail";
// export { Bookmarks } from "./Bookmarks";
export { NotFound } from "./NotFound";
